# commit to be tagged for the new release
commit = "HEAD"

project_name = "go-blockdevice"
github_repo = "siderolabs/go-blockdevice"
match_deps = "^github.com/(siderolabs/[a-zA-Z0-9-]+)$"

# previous = -
# pre_release = true

# [notes]
